---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-lifecycle-suse-com-v1alpha1-upgradeplan
  failurePolicy: Fail
  name: vupgradeplan.kb.io
  rules:
  - apiGroups:
    - lifecycle.suse.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - upgradeplans
  sideEffects: None
